### ISSUE TITLE
app crashes on  heroku 

### ISSUE THREAD

**Issue by patrickvinograd** [adhocteam/va-mobile-sampleweb#1]
App periodically crashes, something is wrong with the error callback chain:
```
2021-05-05T21:49:01.067895+00:00 app[web.1]: TypeError: Cannot read property 'refresh_token' of undefined
2021-05-05T21:49:01.067908+00:00 app[web.1]: at /app/index.js:188:54
2021-05-05T21:49:01.067909+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2021-05-05T21:49:01.067909+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:137:13)
2021-05-05T21:49:01.067910+00:00 app[web.1]: at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2021-05-05T21:49:01.067910+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2021-05-05T21:49:01.067910+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:281:22
2021-05-05T21:49:01.067911+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2021-05-05T21:49:01.067911+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2021-05-05T21:49:01.067912+00:00 app[web.1]: at SessionStrategy.strategy.pass (/app/node_modules/passport/lib/middleware/authenticate.js:343:9)
2021-05-05T21:49:01.067912+00:00 app[web.1]: at SessionStrategy.authenticate (/app/node_modules/passport/lib/strategies/session.js:75:10)
2021-05-05T21:49:01.076030+00:00 heroku[router]: at=info method=GET path="/auth/refresh" host=va-mobile-cutter.herokuapp.com request_id=dacacd2d-306a-4965-86bf-8e0d5719da8d fwd="75.118.52.18" dyno=web.1 connect=0ms service=34ms status=500 bytes=569 protocol=https
2021-05-05T21:49:01.118654+00:00 app[web.1]: /app/node_modules/express/lib/response.js:1007
2021-05-05T21:49:01.118656+00:00 app[web.1]: if (err) return req.next(err);
2021-05-05T21:49:01.118656+00:00 app[web.1]: ^
2021-05-05T21:49:01.118657+00:00 app[web.1]:
2021-05-05T21:49:01.118657+00:00 app[web.1]: TypeError: req.next is not a function
2021-05-05T21:49:01.118658+00:00 app[web.1]: at done (/app/node_modules/express/lib/response.js:1007:25)
2021-05-05T21:49:01.118658+00:00 app[web.1]: at /app/node_modules/hbs/lib/hbs.js:102:16
2021-05-05T21:49:01.118659+00:00 app[web.1]: at /app/node_modules/hbs/lib/hbs.js:93:9
2021-05-05T21:49:01.118659+00:00 app[web.1]: at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
2021-05-05T21:49:01.133747+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-05-05T21:49:01.134105+00:00 app[web.1]: npm ERR! errno 1
2021-05-05T21:49:01.139618+00:00 app[web.1]: npm ERR! va-mobile-sampleweb@1.0.0 start: `node index.js`
2021-05-05T21:49:01.139749+00:00 app[web.1]: npm ERR! Exit status 1
2021-05-05T21:49:01.139894+00:00 app[web.1]: npm ERR!
2021-05-05T21:49:01.140004+00:00 app[web.1]: npm ERR! Failed at the va-mobile-sampleweb@1.0.0 start script.
2021-05-05T21:49:01.140104+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-05-05T21:49:01.145554+00:00 app[web.1]:
2021-05-05T21:49:01.145739+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-05-05T21:49:01.145857+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-05-05T21_49_01_140Z-debug.log
2021-05-05T21:49:01.201921+00:00 heroku[web.1]: Process exited with status 1
2021-05-05T21:49:01.305276+00:00 heroku[web.1]: State changed from up to crashed
2021-05-05T21:49:02.252414+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=va-mobile-cutter.herokuapp.com request_id=916fc90b-3940-4583-8e40-ed0e0663bf76 fwd="75.118.52.18" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by patrickvinograd** [comment]
App has evolved since this was filed, closing
